
# Custom Exception
def CustomException(Exception):
    pass

def causeerror():
    raise CustomException('you called the causeerror function!')

causeerror()



# Adding Attributes
